import type { Zone, Arsalan, Pandal } from "./types";

// Seed data assembled from public 2024/2025 pandal-hopping guides + Arsalan's own branch list.
// Coordinates are best-effort area centroids — the admin's "Fetch missing from Google" button
// snaps them onto the actual verified Google Places pin, along with photo + rating + map link.

export const ZONES: Zone[] = [
  { id: "north",     name: "North",         nameBn: "উত্তর",        color: "#E9C15B" },
  { id: "south",     name: "South",         nameBn: "দক্ষিণ",       color: "#f5d070" },
  { id: "behala",    name: "Behala",        nameBn: "বেহালা",       color: "#d4a843" },
  { id: "central",   name: "Central",       nameBn: "মধ্য",          color: "#c471ed" },
  { id: "saltlake",  name: "Salt Lake",     nameBn: "সল্টলেক",     color: "#4285f4" },
];

// ── Arsalan Restaurant & Caterer — 12 Kolkata branches (as of 2026) ──────────
export const ARSALANS: Arsalan[] = [
  { id: "ars-park",       zoneId: "central",  name: "Arsalan Park Circus / Park Street", shortName: "Park Street",
    placeName: "Arsalan Restaurant & Caterer, 191 Park Street, Kolkata",
    mapsLink: "", rating: 4.4, lat: 22.5464, lng: 88.3595,
    openHours: "11 AM – 2 AM", waitMin: 25 },
  { id: "ars-circus",     zoneId: "south",    name: "Arsalan Circus Avenue", shortName: "Circus Avenue",
    placeName: "Arsalan Restaurant Circus Avenue Park Circus Kolkata",
    mapsLink: "", rating: 4.3, lat: 22.5395, lng: 88.3708,
    openHours: "11 AM – 2 AM", waitMin: 22 },
  { id: "ars-ripon",      zoneId: "central",  name: "Arsalan Ripon Street / Russell Street", shortName: "Ripon Street",
    placeName: "Arsalan Restaurant Ripon Street Kolkata",
    mapsLink: "", rating: 4.2, lat: 22.5559, lng: 88.3541,
    openHours: "11 AM – 2 AM", waitMin: 20 },
  { id: "ars-newalipore", zoneId: "behala",   name: "Arsalan Diamond Harbour Road / New Alipore", shortName: "New Alipore",
    placeName: "Arsalan Restaurant Diamond Harbour Road New Alipore Kolkata",
    mapsLink: "", rating: 4.2, lat: 22.5045, lng: 88.3080,
    openHours: "11 AM – 2 AM", waitMin: 18 },
  { id: "ars-shyam",      zoneId: "north",    name: "Arsalan Hatibagan / Shyambazar", shortName: "Shyambazar",
    placeName: "Arsalan Restaurant 138 Bidhan Sarani Hatibagan Shyambazar Kolkata",
    mapsLink: "", rating: 4.3, lat: 22.5977, lng: 88.3690,
    openHours: "11 AM – 2 AM", waitMin: 24 },
  { id: "ars-newtown",    zoneId: "saltlake", name: "Arsalan Chinar Park / New Town", shortName: "Chinar Park",
    placeName: "Arsalan Restaurant Chinar Park New Town Rajarhat Kolkata",
    mapsLink: "", rating: 4.2, lat: 22.6215, lng: 88.4515,
    openHours: "11 AM – 2 AM", waitMin: 20 },
  { id: "ars-dumdum",     zoneId: "north",    name: "Arsalan Jessore Road / Dumdum", shortName: "Dumdum",
    placeName: "Arsalan Restaurant Jessore Road Shyam Nagar Dumdum Kolkata",
    mapsLink: "", rating: 4.1, lat: 22.6465, lng: 88.4265,
    openHours: "11 AM – 2 AM", waitMin: 18 },
  { id: "ars-ruby",       zoneId: "south",    name: "Arsalan Ruby / EM Bypass / Kasba", shortName: "Ruby",
    placeName: "Arsalan Restaurant Ruby Hospital EM Bypass Kasba Kolkata",
    mapsLink: "", rating: 4.3, lat: 22.5155, lng: 88.3985,
    openHours: "11 AM – 2 AM", waitMin: 22 },
  { id: "ars-jadavpur",   zoneId: "south",    name: "Arsalan Jadavpur / Jodhpur Park / Prince Anwar Shah", shortName: "Jadavpur",
    placeName: "Arsalan Restaurant Prince Anwar Shah Road Jadavpur Kolkata",
    mapsLink: "", rating: 4.2, lat: 22.4972, lng: 88.3700,
    openHours: "11 AM – 2 AM", waitMin: 20 },
  { id: "ars-dhakuria",   zoneId: "south",    name: "Arsalan Dhakuria / Dhankal", shortName: "Dhakuria",
    placeName: "Arsalan Restaurant Dhakuria Kolkata",
    mapsLink: "", rating: 4.1, lat: 22.4970, lng: 88.3766,
    openHours: "11 AM – 2 AM", waitMin: 18 },
  { id: "ars-barrackpore", zoneId: "north",   name: "Arsalan Barrackpore", shortName: "Barrackpore",
    placeName: "Arsalan Restaurant Barrackpore Kolkata",
    mapsLink: "", rating: 4.0, lat: 22.7597, lng: 88.3697,
    openHours: "11 AM – 2 AM", waitMin: 15 },
  { id: "ars-sodepur",    zoneId: "north",    name: "Arsalan Sodepur", shortName: "Sodepur",
    placeName: "Arsalan Restaurant Sodepur Kolkata",
    mapsLink: "", rating: 4.0, lat: 22.7040, lng: 88.3899,
    openHours: "11 AM – 2 AM", waitMin: 15 },
];

// ── Pandals ─────────────────────────────────────────────────────────────────
export const PANDALS: Pandal[] = [
  // ─── NORTH KOLKATA (Shyambazar / Kumartuli / Belgachia axis) ───
  { id: "p-bagbazar",    zoneId: "north", name: "Bagbazar Sarbojanin",   nameBn: "বাগবাজার সর্বজনীন",
    placeName: "Bagbazar Sarbojanin Durga Puja",       mapsLink: "", rating: 4.7,
    lat: 22.6006, lng: 88.3653, theme: "Meenakshi Temple", queueMin: 45, crowd: 5, arsalanId: "ars-shyam" },
  { id: "p-kumartuli",   zoneId: "north", name: "Kumartuli Park",         nameBn: "কুমারটুলি পার্ক",
    placeName: "Kumartuli Park Sarbojanin Durgotsab",   mapsLink: "", rating: 4.6,
    lat: 22.6013, lng: 88.3628, theme: "Artisan quarter", queueMin: 35, crowd: 4, arsalanId: "ars-shyam" },
  { id: "p-kumartuli-s", zoneId: "north", name: "Kumartuli Sarbojanin",   nameBn: "কুমারটুলি সর্বজনীন",
    placeName: "Kumartuli Sarbojanin Durga Puja",       mapsLink: "", rating: 4.5,
    lat: 22.6009, lng: 88.3603, theme: "Master craft",   queueMin: 30, crowd: 4, arsalanId: "ars-shyam" },
  { id: "p-ahiritola",   zoneId: "north", name: "Ahiritola Sarbojanin",   nameBn: "আহিরীটোলা সর্বজনীন",
    placeName: "Ahiritola Sarbojanin Durga Puja",       mapsLink: "", rating: 4.5,
    lat: 22.5924, lng: 88.3617, theme: "River ghat",     queueMin: 30, crowd: 3, arsalanId: "ars-shyam" },
  { id: "p-hatibagan-s", zoneId: "north", name: "Hatibagan Sarbojanin",   nameBn: "হাতিবাগান সর্বজনীন",
    placeName: "Hatibagan Sarbojanin Durga Puja",       mapsLink: "", rating: 4.6,
    lat: 22.5983, lng: 88.3745, theme: "Athaha Ghat Katha", queueMin: 40, crowd: 4, arsalanId: "ars-shyam" },
  { id: "p-hatibagan-n", zoneId: "north", name: "Hatibagan Nabin Pally",  nameBn: "হাতিবাগান নবীন পল্লী",
    placeName: "Hatibagan Nabin Pally Puja",             mapsLink: "", rating: 4.4,
    lat: 22.5991, lng: 88.3735, theme: "Modernist",      queueMin: 25, crowd: 3, arsalanId: "ars-shyam" },
  { id: "p-sreebhumi",   zoneId: "north", name: "Sreebhumi Sporting Club", nameBn: "শ্রীভূমি স্পোর্টিং ক্লাব",
    placeName: "Sreebhumi Sporting Club Durga Puja Lake Town", mapsLink: "", rating: 4.8,
    lat: 22.6165, lng: 88.3990, theme: "Mahishmati Palace (2026)", queueMin: 90, crowd: 5, arsalanId: "ars-dumdum" },
  { id: "p-jagat",       zoneId: "north", name: "Jagat Mukherjee Park",   nameBn: "জগৎ মুখার্জি পার্ক",
    placeName: "Jagat Mukherjee Park Durga Puja",       mapsLink: "", rating: 4.6,
    lat: 22.6112, lng: 88.3648, theme: "AI: Blessing or Curse?", queueMin: 40, crowd: 4, arsalanId: "ars-shyam" },
  { id: "p-kashi",       zoneId: "north", name: "Kashi Bose Lane",        nameBn: "কাশী বসু লেন",
    placeName: "Kashi Bose Lane Durgotsav",             mapsLink: "", rating: 4.5,
    lat: 22.6015, lng: 88.3722, theme: "Artistic excellence", queueMin: 35, crowd: 4, arsalanId: "ars-shyam" },
  { id: "p-telengabagan", zoneId: "north", name: "Telengabagan",           nameBn: "তেলেঙ্গাবাগান",
    placeName: "Telengabagan Sarbojanin Durga Puja",    mapsLink: "", rating: 4.6,
    lat: 22.5979, lng: 88.3843, theme: "Achlaitan (Mobility)", queueMin: 30, crowd: 4, arsalanId: "ars-shyam" },
  { id: "p-tala-p",      zoneId: "north", name: "Tala Prattoy",           nameBn: "তালা প্রত্যয়",
    placeName: "Tala Prattoy Durga Puja",                mapsLink: "", rating: 4.7,
    lat: 22.6135, lng: 88.3777, theme: "Craft revival",  queueMin: 45, crowd: 4, arsalanId: "ars-shyam" },
  { id: "p-chaltabagan", zoneId: "north", name: "Chaltabagan Lohapatti",  nameBn: "চালতাবাগান",
    placeName: "Chaltabagan Lohapatti Sarbojanin",       mapsLink: "", rating: 4.4,
    lat: 22.5945, lng: 88.3736, theme: "Iron workers",   queueMin: 20, crowd: 3, arsalanId: "ars-shyam" },
  { id: "p-dumdum-td",   zoneId: "north", name: "Dum Dum Park Tarun Dal", nameBn: "দমদম পার্ক তরুণ দল",
    placeName: "Dum Dum Park Tarun Dal Durga Puja",     mapsLink: "", rating: 4.5,
    lat: 22.6218, lng: 88.3947, theme: "Conceptual art", queueMin: 35, crowd: 4, arsalanId: "ars-dumdum" },
  { id: "p-dumdum-ts",   zoneId: "north", name: "Dum Dum Park Tarun Sangha", nameBn: "দমদম পার্ক তরুণ সংঘ",
    placeName: "Dum Dum Park Tarun Sangha Durga Puja",  mapsLink: "", rating: 4.5,
    lat: 22.6222, lng: 88.3952, theme: "Satyanweshi Byomkesh", queueMin: 30, crowd: 4, arsalanId: "ars-dumdum" },
  { id: "p-karbagan",    zoneId: "north", name: "Karbagan Sarbojanin",     nameBn: "কারবাগান সর্বজনীন",
    placeName: "Karbagan Sarbojanin Durga Puja",         mapsLink: "", rating: 4.3,
    lat: 22.6035, lng: 88.3820, theme: "Traditional",    queueMin: 25, crowd: 3, arsalanId: "ars-shyam" },
  { id: "p-beniatola",   zoneId: "north", name: "Beniatola Sarbojanin",    nameBn: "বেণিয়াটোলা",
    placeName: "Beniatola Sarbojanin Durga Puja",        mapsLink: "", rating: 4.3,
    lat: 22.5987, lng: 88.3593, theme: "Heritage decor", queueMin: 20, crowd: 3, arsalanId: "ars-shyam" },
  { id: "p-nalin",       zoneId: "north", name: "Nalin Sarkar Street",     nameBn: "নলিন সরকার স্ট্রীট",
    placeName: "Nalin Sarkar Street Durga Puja",         mapsLink: "", rating: 4.2,
    lat: 22.5967, lng: 88.3745, theme: "Heritage",       queueMin: 20, crowd: 3, arsalanId: "ars-shyam" },
  { id: "p-simla",       zoneId: "north", name: "Simla Byayam Samity",     nameBn: "সিমলা ব্যায়াম সমিতি",
    placeName: "Simla Byayam Samity Durga Puja",         mapsLink: "", rating: 4.4,
    lat: 22.5924, lng: 88.3625, theme: "Community",      queueMin: 25, crowd: 3, arsalanId: "ars-shyam" },
  { id: "p-sikdar",      zoneId: "north", name: "Sikdar Bagan Sadharan",   nameBn: "সিকদার বাগান সাধারণ",
    placeName: "Sikdar Bagan Sadharan Durgotsav",        mapsLink: "", rating: 4.5,
    lat: 22.5985, lng: 88.3757, theme: "Century-old spiritual", queueMin: 30, crowd: 3, arsalanId: "ars-shyam" },
  { id: "p-laketown",    zoneId: "north", name: "Lake Town Adhibasi Brinda", nameBn: "লেক টাউন অধিবাসী বৃন্দ",
    placeName: "Lake Town Adhibasi Brinda Durga Puja",   mapsLink: "", rating: 4.4,
    lat: 22.6115, lng: 88.4030, theme: "Social awareness", queueMin: 25, crowd: 3, arsalanId: "ars-dumdum" },
  { id: "p-manicktala",  zoneId: "north", name: "Manicktala Chaltabagan Lohapatty", nameBn: "মানিকতলা চালতাবাগান লোহাপট্টি",
    placeName: "Manicktala Chaltabagan Lohapatty Durga Puja", mapsLink: "", rating: 4.5,
    lat: 22.5875, lng: 88.3800, theme: "Award-winning setup", queueMin: 30, crowd: 3, arsalanId: "ars-shyam" },
  { id: "p-gouriberia",  zoneId: "north", name: "Gouriberia Sarbojanin",   nameBn: "গৌরীবেড়িয়া সর্বজনীন",
    placeName: "Gouriberia Sarbojanin Durga Puja",       mapsLink: "", rating: 4.3,
    lat: 22.5993, lng: 88.3717, theme: "Heritage rooted", queueMin: 20, crowd: 3, arsalanId: "ars-shyam" },

  // ─── SOUTH KOLKATA (Kalighat / Gariahat / Bhawanipur axis) ───
  { id: "p-ekdalia",     zoneId: "south", name: "Ekdalia Evergreen",       nameBn: "একডালিয়া এভারগ্রিন",
    placeName: "Ekdalia Evergreen Club Puja",            mapsLink: "", rating: 4.8,
    lat: 22.5202, lng: 88.3712, theme: "Jagannath Mandir", queueMin: 60, crowd: 5, arsalanId: "ars-circus" },
  { id: "p-singhi",      zoneId: "south", name: "Singhi Park",             nameBn: "সিংহী পার্ক",
    placeName: "Singhi Park Sarbojanin Durgotsav",       mapsLink: "", rating: 4.7,
    lat: 22.5195, lng: 88.3660, theme: "Grand pandal",   queueMin: 50, crowd: 4, arsalanId: "ars-circus" },
  { id: "p-tridhara",    zoneId: "south", name: "Tridhara Sammilani",      nameBn: "ত্রিধারা সম্মিলনী",
    placeName: "Tridhara Sammilani Durga Puja",          mapsLink: "", rating: 4.6,
    lat: 22.5203, lng: 88.3600, theme: "Angan (Courtyard)", queueMin: 40, crowd: 4, arsalanId: "ars-circus" },
  { id: "p-deshapriya",  zoneId: "south", name: "Deshapriya Park",         nameBn: "দেশপ্রিয় পার্ক",
    placeName: "Deshapriya Park Puja",                   mapsLink: "", rating: 4.5,
    lat: 22.5209, lng: 88.3583, theme: "Iconic idol",    queueMin: 55, crowd: 5, arsalanId: "ars-circus" },
  { id: "p-ballygunge",  zoneId: "south", name: "Ballygunge Cultural",     nameBn: "বালিগঞ্জ কালচারাল",
    placeName: "Ballygunge Cultural Association Puja",   mapsLink: "", rating: 4.7,
    lat: 22.5228, lng: 88.3684, theme: "Arshinagar (hall of mirrors)", queueMin: 45, crowd: 4, arsalanId: "ars-circus" },
  { id: "p-mudiali",     zoneId: "south", name: "Mudiali Club",            nameBn: "মুদিয়ালী ক্লাব",
    placeName: "Mudiali Club Durga Puja",                mapsLink: "", rating: 4.4,
    lat: 22.5076, lng: 88.3496, theme: "Craftwork",      queueMin: 30, crowd: 3, arsalanId: "ars-jadavpur" },
  { id: "p-shibmandir",  zoneId: "south", name: "Shib Mandir",             nameBn: "শিবমন্দির",
    placeName: "Shib Mandir Sarbojanin Durga Puja",      mapsLink: "", rating: 4.5,
    lat: 22.5088, lng: 88.3495, theme: "Temple form",    queueMin: 30, crowd: 3, arsalanId: "ars-jadavpur" },
  { id: "p-suruchi",     zoneId: "south", name: "Suruchi Sangha",          nameBn: "সুরুচি সংঘ",
    placeName: "Suruchi Sangha New Alipore Durga Puja",  mapsLink: "", rating: 4.7,
    lat: 22.5081, lng: 88.3300, theme: "Tradition + tech", queueMin: 50, crowd: 4, arsalanId: "ars-newalipore" },
  { id: "p-chetla",      zoneId: "south", name: "Chetla Agrani Club",      nameBn: "চেতলা অগ্রনী",
    placeName: "Chetla Agrani Club Durga Puja",          mapsLink: "", rating: 4.6,
    lat: 22.5147, lng: 88.3372, theme: "Social message", queueMin: 40, crowd: 4, arsalanId: "ars-newalipore" },
  { id: "p-66pally",     zoneId: "south", name: "66 Pally",                nameBn: "৬৬ পল্লী",
    placeName: "66 Pally Sarbojanin Durga Puja",         mapsLink: "", rating: 4.5,
    lat: 22.5117, lng: 88.3568, theme: "Community",      queueMin: 35, crowd: 4, arsalanId: "ars-circus" },
  { id: "p-badamtala",   zoneId: "south", name: "Badamtala Ashar Sangha",  nameBn: "বাদামতলা আষাঢ় সংঘ",
    placeName: "Badamtala Ashar Sangha Durga Puja",      mapsLink: "", rating: 4.5,
    lat: 22.5142, lng: 88.3597, theme: "Artistic",       queueMin: 30, crowd: 3, arsalanId: "ars-circus" },
  { id: "p-bosepukur-s", zoneId: "south", name: "Bosepukur Sitala Mandir", nameBn: "বোসপুকুর শীতলা মন্দির",
    placeName: "Bosepukur Sitala Mandir Durga Puja",     mapsLink: "", rating: 4.6,
    lat: 22.5074, lng: 88.3805, theme: "Village",        queueMin: 35, crowd: 4, arsalanId: "ars-ruby" },
  { id: "p-bosepukur-t", zoneId: "south", name: "Bosepukur Talbagan",      nameBn: "বোসপুকুর তালবাগান",
    placeName: "Bosepukur Talbagan Durga Puja",          mapsLink: "", rating: 4.5,
    lat: 22.5065, lng: 88.3831, theme: "Rooted craft",   queueMin: 30, crowd: 3, arsalanId: "ars-ruby" },
  { id: "p-samajsebi",   zoneId: "south", name: "Samaj Sebi Sangha",       nameBn: "সমাজসেবী সংঘ",
    placeName: "Samaj Sebi Sangha Durga Puja",           mapsLink: "", rating: 4.5,
    lat: 22.5215, lng: 88.3721, theme: "Social service", queueMin: 30, crowd: 3, arsalanId: "ars-circus" },
  { id: "p-hindpark",    zoneId: "south", name: "Hindustan Park",          nameBn: "হিন্দুস্তান পার্ক",
    placeName: "Hindustan Park Sarbojanin Durga Puja",   mapsLink: "", rating: 4.4,
    lat: 22.5205, lng: 88.3648, theme: "Cultural roots", queueMin: 25, crowd: 3, arsalanId: "ars-circus" },
  { id: "p-naktala",     zoneId: "south", name: "Naktala Udayan Sangha",   nameBn: "নাকতলা উদয়ন সংঘ",
    placeName: "Naktala Udayan Sangha Durga Puja",       mapsLink: "", rating: 4.7,
    lat: 22.4855, lng: 88.3711, theme: "Concept art",    queueMin: 50, crowd: 4, arsalanId: "ars-jadavpur" },
  { id: "p-maddox",      zoneId: "south", name: "Maddox Square",           nameBn: "ম্যাডক্স স্কোয়ার",
    placeName: "Maddox Square Durga Puja",                mapsLink: "", rating: 4.4,
    lat: 22.5354, lng: 88.3597, theme: "Adda spot",      queueMin: 25, crowd: 4, arsalanId: "ars-ripon" },
  { id: "p-bakul",       zoneId: "south", name: "Bakul Bagan",             nameBn: "বকুল বাগান",
    placeName: "Bakul Bagan Sarbojanin Durga Puja",      mapsLink: "", rating: 4.4,
    lat: 22.5327, lng: 88.3546, theme: "Neighbourhood",  queueMin: 20, crowd: 3, arsalanId: "ars-ripon" },
  { id: "p-75pally",     zoneId: "south", name: "75 Pally Bhawanipur",     nameBn: "৭৫ পল্লী ভবানীপুর",
    placeName: "75 Pally Sarbojanin Bhawanipur Durga Puja", mapsLink: "", rating: 4.3,
    lat: 22.5354, lng: 88.3510, theme: "Aitijhya Beche Thakuk", queueMin: 20, crowd: 3, arsalanId: "ars-ripon" },
  { id: "p-babubagan",   zoneId: "south", name: "Babubagan Club",           nameBn: "বাবুবাগান ক্লাব",
    placeName: "Babubagan Club Sarbojanin Durga Puja Jadavpur", mapsLink: "", rating: 4.5,
    lat: 22.4972, lng: 88.3730, theme: "Temple replicas", queueMin: 30, crowd: 3, arsalanId: "ars-jadavpur" },
  { id: "p-jodhpur",     zoneId: "south", name: "Jodhpur Park",             nameBn: "যোধপুর পার্ক",
    placeName: "Jodhpur Park Sarbojanin Durga Puja",     mapsLink: "", rating: 4.4,
    lat: 22.5060, lng: 88.3690, theme: "Modern craft",   queueMin: 25, crowd: 3, arsalanId: "ars-jadavpur" },
  { id: "p-alipore",     zoneId: "south", name: "Alipore Sarbojanin",       nameBn: "আলিপুর সর্বজনীন",
    placeName: "Alipore Sarbojanin Durga Puja",           mapsLink: "", rating: 4.3,
    lat: 22.5320, lng: 88.3395, theme: "Traditional",    queueMin: 20, crowd: 3, arsalanId: "ars-ripon" },
  { id: "p-hindclub",    zoneId: "south", name: "Hindustan Club",           nameBn: "হিন্দুস্তান ক্লাব",
    placeName: "Hindustan Club Sarat Bose Road Durga Puja", mapsLink: "", rating: 4.4,
    lat: 22.5315, lng: 88.3585, theme: "Thematic",       queueMin: 25, crowd: 3, arsalanId: "ars-ripon" },

  // ─── BEHALA (Barisha / Behala / Thakurpukur axis) ───
  { id: "p-barisha",     zoneId: "behala", name: "Barisha Club",           nameBn: "বড়িশা ক্লাব",
    placeName: "Barisha Club Durga Puja",                mapsLink: "", rating: 4.7,
    lat: 22.4919, lng: 88.3086, theme: "Concept art",    queueMin: 40, crowd: 4, arsalanId: "ars-newalipore" },
  { id: "p-behala-fc",   zoneId: "behala", name: "Behala Friends Club",    nameBn: "বেহালা ফ্রেন্ডস ক্লাব",
    placeName: "Behala Friends Club Durga Puja",         mapsLink: "", rating: 4.6,
    lat: 22.5015, lng: 88.3105, theme: "Innovative",     queueMin: 35, crowd: 4, arsalanId: "ars-newalipore" },
  { id: "p-behala-nd",   zoneId: "behala", name: "Behala Nutan Dal",       nameBn: "বেহালা নূতন দল",
    placeName: "Behala Nutan Dal Durga Puja",            mapsLink: "", rating: 4.5,
    lat: 22.5008, lng: 88.3100, theme: "Sculptural",     queueMin: 25, crowd: 3, arsalanId: "ars-newalipore" },
  { id: "p-behala-ns",   zoneId: "behala", name: "Behala Notun Sangha",    nameBn: "বেহালা নূতন সংঘ",
    placeName: "Behala Notun Sangha Durga Puja",         mapsLink: "", rating: 4.4,
    lat: 22.5000, lng: 88.3140, theme: "Social message", queueMin: 25, crowd: 3, arsalanId: "ars-newalipore" },
  { id: "p-33pally",     zoneId: "behala", name: "33 Pally",               nameBn: "৩৩ পল্লী",
    placeName: "33 Pally Sarbojanin Behala Durga Puja",  mapsLink: "", rating: 4.4,
    lat: 22.5005, lng: 88.3122, theme: "Elegant",        queueMin: 25, crowd: 3, arsalanId: "ars-newalipore" },
  { id: "p-sarsuna",     zoneId: "behala", name: "Sarsuna Club",           nameBn: "সরসুনা ক্লাব",
    placeName: "Sarsuna Club Durga Puja",                mapsLink: "", rating: 4.4,
    lat: 22.4880, lng: 88.3067, theme: "Eco theme",      queueMin: 25, crowd: 3, arsalanId: "ars-newalipore" },
  { id: "p-buroshib",    zoneId: "behala", name: "Buroshibtala Janakalyan", nameBn: "বুড়োশিবতলা জনকল্যাণ",
    placeName: "Buroshibtala Janakalyan Puja",           mapsLink: "", rating: 4.4,
    lat: 22.4955, lng: 88.3055, theme: "Village",        queueMin: 30, crowd: 3, arsalanId: "ars-newalipore" },
  { id: "p-sakher",      zoneId: "behala", name: "Sakher Bazar Sarbojanin", nameBn: "সখের বাজার সর্বজনীন",
    placeName: "Sakher Bazar Sarbojanin Durgotsav",       mapsLink: "", rating: 4.4,
    lat: 22.4870, lng: 88.3178, theme: "Mythology",      queueMin: 25, crowd: 3, arsalanId: "ars-newalipore" },
  { id: "p-naskar",      zoneId: "behala", name: "Naskar Para Sarbojanin", nameBn: "নাসকার পাড়া সর্বজনীন",
    placeName: "Naskar Para Sarbojanin Durgotsav",       mapsLink: "", rating: 4.3,
    lat: 22.5100, lng: 88.3070, theme: "Experimental",   queueMin: 20, crowd: 3, arsalanId: "ars-newalipore" },
  { id: "p-parnasree",   zoneId: "behala", name: "Parnasree Pally",         nameBn: "পর্ণশ্রী পল্লী",
    placeName: "Parnasree Pally Durga Puja",              mapsLink: "", rating: 4.3,
    lat: 22.4870, lng: 88.3150, theme: "Environment",    queueMin: 25, crowd: 3, arsalanId: "ars-newalipore" },
  { id: "p-haridevpur",  zoneId: "behala", name: "Haridevpur Ajeya Sanghati", nameBn: "হরিদেবপুর অজেয় সংহতি",
    placeName: "Haridevpur Ajeya Sanghati Durga Puja",   mapsLink: "", rating: 4.5,
    lat: 22.4762, lng: 88.3299, theme: "Storytelling",   queueMin: 30, crowd: 3, arsalanId: "ars-newalipore" },
  { id: "p-thakurpukur", zoneId: "behala", name: "Thakurpukur SB Park",     nameBn: "ঠাকুরপুকুর এসবি পার্ক",
    placeName: "Thakurpukur SB Park Sarbojanin Durga Puja", mapsLink: "", rating: 4.5,
    lat: 22.4620, lng: 88.3115, theme: "Modern",         queueMin: 30, crowd: 3, arsalanId: "ars-newalipore" },

  // ─── CENTRAL KOLKATA ───
  { id: "p-santoshm",    zoneId: "central", name: "Santosh Mitra Square",  nameBn: "সন্তোষ মিত্র স্কোয়ার",
    placeName: "Santosh Mitra Square Durga Puja",        mapsLink: "", rating: 4.7,
    lat: 22.5711, lng: 88.3702, theme: "Light spectacle", queueMin: 55, crowd: 5, arsalanId: "ars-park" },
  { id: "p-mdali",       zoneId: "central", name: "Mohammad Ali Park",     nameBn: "মহম্মদ আলী পার্ক",
    placeName: "Mohammad Ali Park Durga Puja",           mapsLink: "", rating: 4.5,
    lat: 22.5769, lng: 88.3567, theme: "Grand",          queueMin: 40, crowd: 4, arsalanId: "ars-ripon" },
  { id: "p-college",     zoneId: "central", name: "College Square",        nameBn: "কলেজ স্কোয়ার",
    placeName: "College Square Durga Puja",              mapsLink: "", rating: 4.6,
    lat: 22.5760, lng: 88.3607, theme: "Angkor Wat",     queueMin: 45, crowd: 4, arsalanId: "ars-ripon" },
  { id: "p-subodhm",     zoneId: "central", name: "Subodh Mallick Square", nameBn: "সুবোধ মল্লিক স্কোয়ার",
    placeName: "Subodh Mallick Square Durga Puja",       mapsLink: "", rating: 4.4,
    lat: 22.5768, lng: 88.3634, theme: "Traditional",    queueMin: 30, crowd: 3, arsalanId: "ars-ripon" },
  { id: "p-sealdah",     zoneId: "central", name: "Sealdah Athletic Club", nameBn: "শিয়ালদহ অ্যাথলেটিক ক্লাব",
    placeName: "Sealdah Athletic Club Durga Puja",       mapsLink: "", rating: 4.3,
    lat: 22.5721, lng: 88.3711, theme: "Sports theme",   queueMin: 20, crowd: 3, arsalanId: "ars-park" },
  { id: "p-taltala",     zoneId: "central", name: "Taltala Sarbojanin",    nameBn: "তালতলা সর্বজনীন",
    placeName: "Taltala Sarbojanin Durga Puja",          mapsLink: "", rating: 4.3,
    lat: 22.5620, lng: 88.3576, theme: "Community",      queueMin: 20, crowd: 3, arsalanId: "ars-park" },

  // ─── SALT LAKE / NEW TOWN ───
  { id: "p-fdblock",     zoneId: "saltlake", name: "FD Block Salt Lake",   nameBn: "এফডি ব্লক সল্টলেক",
    placeName: "FD Block Sarbojanin Durgotsav Salt Lake", mapsLink: "", rating: 4.6,
    lat: 22.5877, lng: 88.4222, theme: "Grand scale",    queueMin: 40, crowd: 4, arsalanId: "ars-newtown" },
  { id: "p-akblock",     zoneId: "saltlake", name: "AK Block Salt Lake",   nameBn: "একে ব্লক সল্টলেক",
    placeName: "AK Block Sarbojanin Durgotsav Salt Lake", mapsLink: "", rating: 4.5,
    lat: 22.5775, lng: 88.4230, theme: "Water conservation", queueMin: 30, crowd: 4, arsalanId: "ars-newtown" },
  { id: "p-ajblock",     zoneId: "saltlake", name: "AJ Block Salt Lake",   nameBn: "এজে ব্লক সল্টলেক",
    placeName: "AJ Block Sarbojanin Durgotsav Salt Lake", mapsLink: "", rating: 4.4,
    lat: 22.5773, lng: 88.4187, theme: "Modernist",      queueMin: 25, crowd: 3, arsalanId: "ars-newtown" },
  { id: "p-newtown",     zoneId: "saltlake", name: "New Town Sarbojanin",  nameBn: "নিউটাউন সর্বজনীন",
    placeName: "New Town Sarbojanin Durga Puja",         mapsLink: "", rating: 4.5,
    lat: 22.5934, lng: 88.4707, theme: "Contemporary",   queueMin: 30, crowd: 3, arsalanId: "ars-newtown" },
];

// Default user location (Park Street / central Kolkata)
export const DEFAULT_USER = { lat: 22.5535, lng: 88.3520 };

export const MENU_SAMPLE = [
  { n: "Mutton Biryani",   price: "₹380" },
  { n: "Chicken Biryani",  price: "₹280" },
  { n: "Chicken Chaap",    price: "₹260" },
  { n: "Mutton Chaap",     price: "₹340" },
  { n: "Kebab Platter",    price: "₹420" },
  { n: "Firni",            price: "₹90"  },
];
